# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f405030953942d8ccbdf2f5727c6fa67acee682292e248566b051bea289a3df8d311445b11b169d7f36e5cbb8d3f302abdf8ffabc962b9e119569b68f4acac93

test:
  secret_key_base: c6ff4f9d90c349d8baa7ed7652d15d043e6c4f0472e249d7cc3bbafc0acbd52aae255e88707ded2f2f240bf5bb0ec1632c52262439921c3c40a0006c52a6a5e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
